/* To insert atleast 5 rows in each table created in the previous task. */


/* DIRECTOR */
INSERT INTO Student_23.Director VALUES (1, 'John', 'Joe', '01, 01, 1980', 'M');
INSERT INTO Student_23.Director VALUES (2, 'Wick', 'Joseph', '02, 02, 1981', 'M');
INSERT INTO Student_23.Director VALUES (3, 'Serah', 'Say', '03, 03, 1982', 'F');
INSERT INTO Student_23.Director VALUES (4, 'Iva', 'Maria', '04, 04, 1983', 'F');
INSERT INTO Student_23.Director VALUES (5, 'Elby', 'Mathew', '05, 05, 1984', 'F');



/* FILM */
INSERT INTO Student_23.FILM (FILM_ID, FILM_NAME, RELEASE_DATE, FILM_DIRECTOR_ID, FILM_LANGUAGE_ID, FILM_COUNTRY_ID, FILM_STUDIO_ID, FILM_CERTIFICATE_ID) 
VALUES (1001, 'Avatar', '18-12-2009', 101, 201, 301, 401, 501);

INSERT INTO Student_23.FILM (FILM_ID, FILM_NAME, RELEASE_DATE, FILM_DIRECTOR_ID, FILM_LANGUAGE_ID, FILM_COUNTRY_ID, FILM_STUDIO_ID, FILM_CERTIFICATE_ID) 
VALUES (1002, 'Titanic', '18-11-1997', 102, 202, 302, 402, 502);

INSERT INTO Student_23.FILM (FILM_ID, FILM_NAME, RELEASE_DATE, FILM_DIRECTOR_ID, FILM_LANGUAGE_ID, FILM_COUNTRY_ID, FILM_STUDIO_ID, FILM_CERTIFICATE_ID) 
VALUES (1003, 'JohnWick', '27-11-2013', 103, 203, 303, 403, 503);

INSERT INTO Student_23.FILM (FILM_ID, FILM_NAME, RELEASE_DATE, FILM_DIRECTOR_ID, FILM_LANGUAGE_ID, FILM_COUNTRY_ID, FILM_STUDIO_ID, FILM_CERTIFICATE_ID) 
VALUES (1004, 'Creed', '22-11-1995', 104, 204, 304, 404, 504);

INSERT INTO Student_23.FILM (FILM_ID, FILM_NAME, RELEASE_DATE, FILM_DIRECTOR_ID, FILM_LANGUAGE_ID, FILM_COUNTRY_ID, FILM_STUDIO_ID, FILM_CERTIFICATE_ID) 
VALUES (1005, 'The Avengers', '25-04-2012', 105, 205, 305, 405, 505);


/* LANGUAGE */
INSERT INTO STUDENT_23.LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE, COUNTRY_OF_ORIGIN, OFFICIAL_STATUS) VALUES (1, 'English', 'en', 'United Kingdom', 'Yes');
INSERT INTO STUDENT_23.LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE, COUNTRY_OF_ORIGIN, OFFICIAL_STATUS) VALUES (2, 'French', 'fr', 'France', 'Yes');
INSERT INTO STUDENT_23.LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE, COUNTRY_OF_ORIGIN, OFFICIAL_STATUS) VALUES (3, 'Spanish', 'es', 'Spain', 'Yes');
INSERT INTO STUDENT_23.LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE, COUNTRY_OF_ORIGIN, OFFICIAL_STATUS) VALUES (4, 'Chinese', 'zh', 'China', 'Yes');
INSERT INTO STUDENT_23.LANGUAGE (LANGUAGE_ID, LANGUAGE_NAME, LANGUAGE_CODE, COUNTRY_OF_ORIGIN, OFFICIAL_STATUS) VALUES (5, 'Hindi', 'hi', 'India', 'Yes');


/* COUNTRY */
INSERT INTO Student_23.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, COUNTRY_LANGUAGE, TIME_ZONE)
VALUES (1, 'India', 'IND', 'Hindi', 'UTC+5:30');

INSERT INTO Student_23.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, COUNTRY_LANGUAGE, TIME_ZONE)
VALUES (2, 'United Kingdom', 'UK', 'English', 'UTC+0');

INSERT INTO Student_23.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, COUNTRY_LANGUAGE, TIME_ZONE)
VALUES (3, 'United States', 'US', 'English', 'UTC-5');

INSERT INTO Student_23.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, COUNTRY_LANGUAGE, TIME_ZONE)
VALUES (4, 'China', 'CHN', 'Mandarin', 'UTC+8');

INSERT INTO Student_23.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, COUNTRY_LANGUAGE, TIME_ZONE)
VALUES (5, 'Japan', 'JPN', 'Japanese', 'UTC+9');

/* STUDIO */
INSERT INTO STUDENT_23.STUDIO (STUDIO_ID, STUDIO_NAME, STUDIO_PHONE_NO, STUDIO_ADRESS, STUDIO_EMAIL)
VALUES (1, 'Universal Pictures', '123-456-7890', '100 Universal City Plaza, Universal City, CA 91608', 'Universal_Pictures@gmail.com');

INSERT INTO STUDENT_23.STUDIO (STUDIO_ID, STUDIO_NAME, STUDIO_PHONE_NO, STUDIO_ADRESS, STUDIO_EMAIL)
VALUES (2, 'Warner Bros. Pictures', '123-456-7891', '4000 Warner Blvd., Burbank, CA 91522', 'Warner_Bros_Pictures@gmail.com');

INSERT INTO STUDENT_23.STUDIO (STUDIO_ID, STUDIO_NAME, STUDIO_PHONE_NO, STUDIO_ADRESS, STUDIO_EMAIL)
VALUES (3, 'Paramount Pictures', '123-456-7892', '5555 Melrose Avenue, Hollywood, CA 90038', 'Paramount_Pictures@gmail.com');

INSERT INTO STUDENT_23.STUDIO (STUDIO_ID, STUDIO_NAME, STUDIO_PHONE_NO, STUDIO_ADRESS, STUDIO_EMAIL)
VALUES (4, 'Disney Pictures', '123-456-7893', '500 South Buena Vista Street, Burbank, CA 91521', 'Disney_Pictures@gmail.com');

INSERT INTO STUDENT_23.STUDIO (STUDIO_ID, STUDIO_NAME, STUDIO_PHONE_NO, STUDIO_ADRESS, STUDIO_EMAIL)
VALUES (5, 'Columbia Pictures', '123-456-7894', '10202 West Washington Boulevard, Culver City, CA 90232', 'Columbia_Pictures@gmail.com');



/* CERTIFICATE */
INSERT INTO Student_23.CERTIFICATE (CERTIFICATE_ID, CERTIFICATE_NAME, CERTIFICATE_DATE, CERTIFICATE_TYPE, EXPIRY_DATE) VALUES (1, 'PG', '20-NOV-2020', 'Film Certificate' , '20-NOV-2021'); 
INSERT INTO Student_23.CERTIFICATE (CERTIFICATE_ID, CERTIFICATE_NAME, CERTIFICATE_DATE, CERTIFICATE_TYPE, EXPIRY_DATE) VALUES (2, 'G', '25-DEC-2020', 'Film Certificate' , '25-DEC-2021');
INSERT INTO Student_23.CERTIFICATE (CERTIFICATE_ID, CERTIFICATE_NAME, CERTIFICATE_DATE, CERTIFICATE_TYPE, EXPIRY_DATE) VALUES (3, 'PG-13', '18-JAN-2021', 'Film Certificate' , '18-JAN-2022');
INSERT INTO Student_23.CERTIFICATE (CERTIFICATE_ID, CERTIFICATE_NAME, CERTIFICATE_DATE, CERTIFICATE_TYPE, EXPIRY_DATE) VALUES (4, 'R', '12-FEB-2021', 'Film Certificate' , '12-FEB-2022');
INSERT INTO Student_23.CERTIFICATE (CERTIFICATE_ID, CERTIFICATE_NAME, CERTIFICATE_DATE, CERTIFICATE_TYPE, EXPIRY_DATE) VALUES (5, 'NC-17', '14-MAR-2021', 'Film Certificate' , '14-MAR-2022');






